-- gruuvy.nvim
-- A minimal, clean dark colorscheme with gruvbox vibes and pastel accents.

local M = {}

M.palette = {
  -- Base
  bg0      = "#262626",  -- main background
  bg1      = "#303030",  -- cursor line, subtle bg
  bg2      = "#3a3a3a",  -- selection, visual
  bg3      = "#4e4e4e",  -- line numbers, borders
  bg4      = "#626262",  -- comments
  fg0      = "#f5eedc",  -- bright foreground
  fg1      = "#e8dcc8",  -- main foreground
  fg2      = "#c8bfaa",  -- dimmed foreground
  fg3      = "#a89f8c",  -- very dimmed

  -- Pastel accents
  red      = "#e88282",  -- pastel rose
  green    = "#a8c8a0",  -- pastel sage green
  yellow   = "#e8d09a",  -- pastel warm yellow
  blue     = "#9ab8d8",  -- pastel steel blue
  purple   = "#c4b5e3",  -- pastel lavender
  aqua     = "#98c8c0",  -- pastel teal
  orange   = "#e0b890",  -- pastel orange (keywords)

  -- Bright variants
  bred     = "#f0b8b8",
  bgreen   = "#b8d8b0",
  byellow  = "#f0dca8",
  bblue    = "#aacce8",
  bpurple  = "#c8b8e8",
  baqua    = "#a8d8d0",
  borange  = "#ecc8a0",

  -- Semantic
  none     = "NONE",
}

function M.setup(opts)
  opts = opts or {}
  local bold = opts.bold and true or false
  local p = M.palette

  -- Reset
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end
  vim.g.colors_name = "gruuvy"
  vim.o.background = "dark"
  vim.o.termguicolors = true

  local hi = function(group, spec)
    vim.api.nvim_set_hl(0, group, spec)
  end

  -- ─── Editor UI ───────────────────────────────────────────────────────
  hi("Normal",          { fg = p.fg1,    bg = p.bg0 })
  hi("NormalNC",        { fg = p.fg2,    bg = p.bg0 })
  hi("NormalFloat",     { fg = p.fg1,    bg = p.bg1 })
  hi("FloatBorder",     { fg = p.bg3,    bg = p.bg1 })
  hi("FloatTitle",      { fg = p.yellow, bg = p.bg1, bold = true })
  hi("Cursor",          { fg = p.bg0,    bg = p.fg1 })
  hi("CursorIM",        { fg = p.bg0,    bg = p.fg1 })
  hi("CursorLine",      { bg = p.bg1 })
  hi("CursorColumn",    { bg = p.bg1 })
  hi("CursorLineNr",    { fg = p.yellow, bg = p.bg1, bold = true })
  hi("LineNr",          { fg = p.bg4 })
  hi("LineNrAbove",     { fg = p.bg4 })
  hi("LineNrBelow",     { fg = p.bg4 })
  hi("SignColumn",      { fg = p.bg3,    bg = p.bg0 })
  hi("ColorColumn",     { bg = p.bg1 })
  hi("Conceal",         { fg = p.bg4 })

  hi("Visual",          { bg = p.bg2 })
  hi("VisualNOS",       { bg = p.bg2 })
  hi("Search",          { fg = p.bg0,    bg = p.yellow })
  hi("CurSearch",       { fg = p.bg0,    bg = p.orange })
  hi("IncSearch",       { fg = p.bg0,    bg = p.orange })
  hi("Substitute",      { fg = p.bg0,    bg = p.red })

  hi("StatusLine",      { fg = p.fg2,    bg = p.bg1 })
  hi("StatusLineNC",    { fg = p.bg4,    bg = p.bg1 })
  hi("WinBar",          { fg = p.fg2,    bg = p.bg0 })
  hi("WinBarNC",        { fg = p.bg4,    bg = p.bg0 })
  hi("WinSeparator",    { fg = p.bg3 })
  hi("VertSplit",       { fg = p.bg3 })

  hi("TabLine",         { fg = p.fg3,    bg = p.bg1 })
  hi("TabLineSel",      { fg = p.fg1,    bg = p.bg0, bold = true })
  hi("TabLineFill",     { bg = p.bg1 })

  hi("Pmenu",           { fg = p.fg1,    bg = p.bg1 })
  hi("PmenuSel",        { fg = p.fg0,    bg = p.bg3, bold = true })
  hi("PmenuSbar",       { bg = p.bg2 })
  hi("PmenuThumb",      { bg = p.bg4 })
  hi("PmenuKind",       { fg = p.aqua,   bg = p.bg1 })
  hi("PmenuKindSel",    { fg = p.aqua,   bg = p.bg3 })
  hi("PmenuExtra",      { fg = p.fg3,    bg = p.bg1 })
  hi("PmenuExtraSel",   { fg = p.fg3,    bg = p.bg3 })

  hi("WildMenu",        { fg = p.bg0,    bg = p.blue })

  hi("Folded",          { fg = p.fg3,    bg = p.bg1 })
  hi("FoldColumn",      { fg = p.bg3,    bg = p.bg0 })

  hi("DiffAdd",         { fg = p.green,  bg = p.bg0 })
  hi("DiffChange",      { fg = p.yellow, bg = p.bg0 })
  hi("DiffDelete",      { fg = p.red,    bg = p.bg0 })
  hi("DiffText",        { fg = p.bg0,    bg = p.yellow })

  hi("SpellBad",        { sp = p.red,    undercurl = true })
  hi("SpellCap",        { sp = p.blue,   undercurl = true })
  hi("SpellRare",       { sp = p.fg1, undercurl = true })
  hi("SpellLocal",      { sp = p.aqua,   undercurl = true })

  hi("Directory",       { fg = p.blue,   bold = true })
  hi("Title",           { fg = p.yellow, bold = true })
  hi("MatchParen",      { fg = p.orange, bold = true, underline = true })

  hi("NonText",         { fg = p.bg3 })
  hi("SpecialKey",      { fg = p.bg3 })
  hi("Whitespace",      { fg = p.bg3 })
  hi("EndOfBuffer",     { fg = p.bg1 })

  hi("Question",        { fg = p.green })
  hi("ModeMsg",         { fg = p.yellow, bold = true })
  hi("MsgArea",         { fg = p.fg2 })
  hi("MoreMsg",         { fg = p.green })
  hi("ErrorMsg",        { fg = p.red })
  hi("WarningMsg",      { fg = p.yellow })

  hi("QuickFixLine",    { bg = p.bg2 })
  hi("qfLineNr",        { fg = p.yellow })

  -- ─── Syntax ──────────────────────────────────────────────────────────
  hi("Comment",         { fg = p.bg4 })
  hi("Constant",        { fg = p.fg1 })
  hi("String",          { fg = p.green })
  hi("Character",       { fg = p.green })
  hi("Number",          { fg = p.fg1 })
  hi("Boolean",         { fg = p.fg1 })
  hi("Float",           { fg = p.fg1 })

  hi("Identifier",      { fg = p.fg1 })
  hi("Function",        { fg = p.fg1 })

  hi("Statement",       { fg = p.red })
  hi("Conditional",     { fg = p.red })
  hi("Repeat",          { fg = p.red })
  hi("Label",           { fg = p.red })
  hi("Operator",        { fg = p.fg1 })
  hi("Keyword",         { fg = p.red })
  hi("Exception",       { fg = p.red })

  hi("PreProc",         { fg = p.aqua })
  hi("Include",         { fg = p.aqua })
  hi("Define",          { fg = p.aqua })
  hi("Macro",           { fg = p.aqua })
  hi("PreCondit",       { fg = p.aqua })

  hi("Type",            { fg = p.yellow })
  hi("StorageClass",    { fg = p.yellow })
  hi("Structure",       { fg = p.yellow })
  hi("Typedef",         { fg = p.yellow })

  hi("Special",         { fg = p.orange })
  hi("SpecialChar",     { fg = p.orange })
  hi("Tag",             { fg = p.orange })
  hi("Delimiter",       { fg = p.fg2 })
  hi("SpecialComment",  { fg = p.bg4,    bold = true })
  hi("Debug",           { fg = p.red })

  hi("Underlined",      { underline = true })
  hi("Bold",            { bold = true })
  hi("Italic",          {})
  hi("Ignore",          { fg = p.bg3 })
  hi("Error",           { fg = p.red,    bold = true })
  hi("Todo",            { fg = p.bg0,    bg = p.yellow, bold = true })

  -- ─── Treesitter ──────────────────────────────────────────────────────
  hi("@variable",                   { fg = p.fg1 })
  hi("@variable.builtin",           { fg = p.orange })
  hi("@variable.parameter",         { fg = p.fg1 })
  hi("@variable.member",            { fg = p.fg1 })

  hi("@constant",                   { fg = p.fg1 })
  hi("@constant.builtin",           { fg = p.purple, bold = bold })
  hi("@constant.macro",             { fg = p.aqua })

  hi("@module",                     { fg = p.fg1 })
  hi("@module.builtin",             { fg = p.orange })
  hi("@label",                      { fg = p.red })

  hi("@string",                     { fg = p.green })
  hi("@string.documentation",       { fg = p.green })
  hi("@string.regexp",              { fg = p.aqua })
  hi("@string.escape",              { fg = p.orange })
  hi("@string.special",             { fg = p.aqua })
  hi("@string.special.url",         { fg = p.blue, underline = true })
  hi("@string.special.symbol",      { fg = p.fg1 })

  hi("@character",                  { fg = p.green })
  hi("@character.special",          { fg = p.orange })
  hi("@boolean",                    { fg = p.fg1 })
  hi("@number",                     { fg = p.fg1 })
  hi("@float",                      { fg = p.fg1 })

  hi("@type",                       { fg = p.yellow })
  hi("@type.builtin",               { fg = p.yellow, bold = bold })
  hi("@type.definition",            { fg = p.yellow })

  hi("@attribute",                  { fg = p.yellow })
  hi("@attribute.builtin",          { fg = p.yellow })
  hi("@property",                   { fg = p.fg1 })

  hi("@function",                   { fg = p.fg1 })
  hi("@function.builtin",           { fg = p.fg1 })
  hi("@function.call",              { fg = p.fg1 })
  hi("@function.macro",             { fg = p.aqua })
  hi("@function.method",            { fg = p.fg1 })
  hi("@function.method.call",       { fg = p.fg1 })

  hi("@constructor",                { fg = p.yellow })
  hi("@operator",                   { fg = p.fg1 })

  hi("@keyword",                    { fg = p.red })
  hi("@keyword.coroutine",          { fg = p.red })
  hi("@keyword.function",           { fg = p.red })
  hi("@keyword.operator",           { fg = p.red })
  hi("@keyword.import",             { fg = p.aqua })
  hi("@keyword.type",               { fg = p.red })
  hi("@keyword.modifier",           { fg = p.red })
  hi("@keyword.repeat",             { fg = p.red })
  hi("@keyword.return",             { fg = p.red })
  hi("@keyword.debug",              { fg = p.red })
  hi("@keyword.exception",          { fg = p.red })
  hi("@keyword.conditional",        { fg = p.red })
  hi("@keyword.conditional.ternary", { fg = p.red })
  hi("@keyword.directive",          { fg = p.aqua })
  hi("@keyword.directive.define",   { fg = p.aqua })

  hi("@punctuation.delimiter",      { fg = p.fg2 })
  hi("@punctuation.bracket",        { fg = p.fg2 })
  hi("@punctuation.special",        { fg = p.orange })

  hi("@comment",                    { fg = p.bg4 })
  hi("@comment.documentation",      { fg = p.bg4 })
  hi("@comment.error",              { fg = p.red, bold = true })
  hi("@comment.warning",            { fg = p.yellow, bold = true })
  hi("@comment.todo",               { fg = p.bg0, bg = p.yellow, bold = true })
  hi("@comment.note",               { fg = p.bg0, bg = p.blue, bold = true })

  hi("@markup.strong",              { bold = true })
  hi("@markup.italic",              {})
  hi("@markup.strikethrough",       { strikethrough = true })
  hi("@markup.underline",           { underline = true })
  hi("@markup.heading",             { fg = p.yellow, bold = true })
  hi("@markup.heading.1",           { fg = p.yellow, bold = true })
  hi("@markup.heading.2",           { fg = p.orange, bold = true })
  hi("@markup.heading.3",           { fg = p.green,  bold = true })
  hi("@markup.heading.4",           { fg = p.blue,   bold = true })
  hi("@markup.heading.5",           { fg = p.fg1, bold = true })
  hi("@markup.heading.6",           { fg = p.aqua,   bold = true })
  hi("@markup.quote",               { fg = p.fg3 })
  hi("@markup.math",                { fg = p.aqua })
  hi("@markup.link",                { fg = p.blue, underline = true })
  hi("@markup.link.label",          { fg = p.blue })
  hi("@markup.link.url",            { fg = p.aqua, underline = true })
  hi("@markup.raw",                 { fg = p.green })
  hi("@markup.raw.block",           { fg = p.green })
  hi("@markup.list",                { fg = p.orange })
  hi("@markup.list.checked",        { fg = p.green })
  hi("@markup.list.unchecked",      { fg = p.fg3 })

  hi("@diff.plus",                  { fg = p.green })
  hi("@diff.minus",                 { fg = p.red })
  hi("@diff.delta",                 { fg = p.yellow })

  hi("@tag",                        { fg = p.orange })
  hi("@tag.builtin",                { fg = p.orange })
  hi("@tag.attribute",              { fg = p.yellow })
  hi("@tag.delimiter",              { fg = p.fg2 })

  -- ─── LSP ─────────────────────────────────────────────────────────────
  hi("LspReferenceText",            { bg = p.bg2 })
  hi("LspReferenceRead",            { bg = p.bg2 })
  hi("LspReferenceWrite",           { bg = p.bg2, underline = true })
  hi("LspSignatureActiveParameter", { fg = p.orange, bold = true })
  hi("LspInlayHint",                { fg = p.bg4, bg = p.bg1 })
  hi("LspCodeLens",                 { fg = p.bg4 })

  -- Diagnostics
  hi("DiagnosticError",             { fg = p.red })
  hi("DiagnosticWarn",              { fg = p.yellow })
  hi("DiagnosticInfo",              { fg = p.blue })
  hi("DiagnosticHint",              { fg = p.aqua })
  hi("DiagnosticOk",                { fg = p.green })
  hi("DiagnosticUnderlineError",    { sp = p.red,    undercurl = true })
  hi("DiagnosticUnderlineWarn",     { sp = p.yellow, undercurl = true })
  hi("DiagnosticUnderlineInfo",     { sp = p.blue,   undercurl = true })
  hi("DiagnosticUnderlineHint",     { sp = p.aqua,   undercurl = true })
  hi("DiagnosticUnnecessary",       { fg = p.fg3 })
  hi("DiagnosticDeprecated",        { fg = p.fg3,    strikethrough = true })
  hi("DiagnosticVirtualTextError",  { fg = p.red,    bg = p.bg1 })
  hi("DiagnosticVirtualTextWarn",   { fg = p.yellow, bg = p.bg1 })
  hi("DiagnosticVirtualTextInfo",   { fg = p.blue,   bg = p.bg1 })
  hi("DiagnosticVirtualTextHint",   { fg = p.aqua,   bg = p.bg1 })
  hi("DiagnosticFloatingError",     { fg = p.red })
  hi("DiagnosticFloatingWarn",      { fg = p.yellow })
  hi("DiagnosticFloatingInfo",      { fg = p.blue })
  hi("DiagnosticFloatingHint",      { fg = p.aqua })
  hi("DiagnosticSignError",         { fg = p.red })
  hi("DiagnosticSignWarn",          { fg = p.yellow })
  hi("DiagnosticSignInfo",          { fg = p.blue })
  hi("DiagnosticSignHint",          { fg = p.aqua })

  -- ─── nvim-cmp ────────────────────────────────────────────────────────
  hi("CmpItemAbbr",                 { fg = p.fg2 })
  hi("CmpItemAbbrDeprecated",       { fg = p.fg3, strikethrough = true })
  hi("CmpItemAbbrMatch",            { fg = p.yellow, bold = true })
  hi("CmpItemAbbrMatchFuzzy",       { fg = p.orange, bold = true })
  hi("CmpItemMenu",                 { fg = p.fg3 })
  hi("CmpItemKindDefault",          { fg = p.fg3 })
  hi("CmpItemKindKeyword",          { fg = p.orange })
  hi("CmpItemKindVariable",         { fg = p.fg1 })
  hi("CmpItemKindConstant",         { fg = p.purple })
  hi("CmpItemKindReference",        { fg = p.fg1 })
  hi("CmpItemKindValue",            { fg = p.purple })
  hi("CmpItemKindFunction",         { fg = p.green })
  hi("CmpItemKindMethod",           { fg = p.green })
  hi("CmpItemKindConstructor",      { fg = p.blue })
  hi("CmpItemKindClass",            { fg = p.blue })
  hi("CmpItemKindInterface",        { fg = p.blue })
  hi("CmpItemKindStruct",           { fg = p.blue })
  hi("CmpItemKindEvent",            { fg = p.orange })
  hi("CmpItemKindEnum",             { fg = p.blue })
  hi("CmpItemKindUnit",             { fg = p.orange })
  hi("CmpItemKindModule",           { fg = p.yellow })
  hi("CmpItemKindProperty",         { fg = p.aqua })
  hi("CmpItemKindField",            { fg = p.aqua })
  hi("CmpItemKindTypeParameter",    { fg = p.blue })
  hi("CmpItemKindEnumMember",       { fg = p.purple })
  hi("CmpItemKindOperator",         { fg = p.fg1 })
  hi("CmpItemKindSnippet",          { fg = p.fg3 })
  hi("CmpItemKindText",             { fg = p.fg2 })
  hi("CmpItemKindFile",             { fg = p.yellow })
  hi("CmpItemKindFolder",           { fg = p.blue })
  hi("CmpItemKindColor",            { fg = p.purple })

  -- ─── blink.cmp ───────────────────────────────────────────────────────
  hi("BlinkCmpLabel",               { fg = p.fg2 })
  hi("BlinkCmpLabelDeprecated",     { fg = p.fg3, strikethrough = true })
  hi("BlinkCmpLabelMatch",          { fg = p.yellow, bold = true })
  hi("BlinkCmpLabelDetail",         { fg = p.fg3 })
  hi("BlinkCmpLabelDescription",    { fg = p.fg3 })
  hi("BlinkCmpKind",                { fg = p.fg3 })
  hi("BlinkCmpKindClass",           { fg = p.blue })
  hi("BlinkCmpKindColor",           { fg = p.purple })
  hi("BlinkCmpKindConstant",        { fg = p.purple })
  hi("BlinkCmpKindConstructor",     { fg = p.blue })
  hi("BlinkCmpKindEnum",            { fg = p.blue })
  hi("BlinkCmpKindEnumMember",      { fg = p.purple })
  hi("BlinkCmpKindEvent",           { fg = p.orange })
  hi("BlinkCmpKindField",           { fg = p.aqua })
  hi("BlinkCmpKindFile",            { fg = p.yellow })
  hi("BlinkCmpKindFolder",          { fg = p.blue })
  hi("BlinkCmpKindFunction",        { fg = p.green })
  hi("BlinkCmpKindInterface",       { fg = p.blue })
  hi("BlinkCmpKindKeyword",         { fg = p.orange })
  hi("BlinkCmpKindMethod",          { fg = p.green })
  hi("BlinkCmpKindModule",          { fg = p.yellow })
  hi("BlinkCmpKindOperator",        { fg = p.fg1 })
  hi("BlinkCmpKindProperty",        { fg = p.aqua })
  hi("BlinkCmpKindReference",       { fg = p.fg1 })
  hi("BlinkCmpKindSnippet",         { fg = p.fg3 })
  hi("BlinkCmpKindStruct",          { fg = p.blue })
  hi("BlinkCmpKindText",            { fg = p.fg2 })
  hi("BlinkCmpKindTypeParameter",   { fg = p.blue })
  hi("BlinkCmpKindUnit",            { fg = p.orange })
  hi("BlinkCmpKindValue",           { fg = p.purple })
  hi("BlinkCmpKindVariable",        { fg = p.fg1 })
  hi("BlinkCmpMenu",                { fg = p.fg1,    bg = p.bg1 })
  hi("BlinkCmpMenuBorder",          { fg = p.bg3,    bg = p.bg1 })
  hi("BlinkCmpMenuSelection",       { fg = p.fg0,    bg = p.bg3, bold = true })
  hi("BlinkCmpScrollBarThumb",      { bg = p.bg4 })
  hi("BlinkCmpScrollBarGutter",     { bg = p.bg1 })
  hi("BlinkCmpDoc",                 { fg = p.fg1,    bg = p.bg1 })
  hi("BlinkCmpDocBorder",           { fg = p.bg3,    bg = p.bg1 })
  hi("BlinkCmpDocSeparator",        { fg = p.bg3,    bg = p.bg1 })
  hi("BlinkCmpDocCursorLine",       { bg = p.bg2 })
  hi("BlinkCmpSignatureHelp",       { fg = p.fg1,    bg = p.bg1 })
  hi("BlinkCmpSignatureHelpBorder", { fg = p.bg3,    bg = p.bg1 })
  hi("BlinkCmpSignatureHelpActiveParameter", { fg = p.orange, bold = true })

  -- ─── Telescope ───────────────────────────────────────────────────────
  hi("TelescopeNormal",             { fg = p.fg1,    bg = p.bg0 })
  hi("TelescopeBorder",             { fg = p.bg3,    bg = p.bg0 })
  hi("TelescopeTitle",              { fg = p.yellow, bg = p.bg0, bold = true })
  hi("TelescopePromptNormal",       { fg = p.fg1,    bg = p.bg1 })
  hi("TelescopePromptBorder",       { fg = p.bg3,    bg = p.bg1 })
  hi("TelescopePromptTitle",        { fg = p.orange, bg = p.bg1, bold = true })
  hi("TelescopePromptPrefix",       { fg = p.orange })
  hi("TelescopePromptCounter",      { fg = p.fg3 })
  hi("TelescopePreviewNormal",      { fg = p.fg1,    bg = p.bg0 })
  hi("TelescopePreviewBorder",      { fg = p.bg3,    bg = p.bg0 })
  hi("TelescopePreviewTitle",       { fg = p.green,  bg = p.bg0, bold = true })
  hi("TelescopePreviewLine",        { bg = p.bg1 })
  hi("TelescopeResultsNormal",      { fg = p.fg1,    bg = p.bg0 })
  hi("TelescopeResultsBorder",      { fg = p.bg3,    bg = p.bg0 })
  hi("TelescopeResultsTitle",       { fg = p.blue,   bg = p.bg0, bold = true })
  hi("TelescopeSelection",          { fg = p.fg0,    bg = p.bg2, bold = true })
  hi("TelescopeSelectionCaret",     { fg = p.orange, bg = p.bg2 })
  hi("TelescopeMultiSelection",     { fg = p.purple, bg = p.bg2 })
  hi("TelescopeMultiIcon",          { fg = p.purple })
  hi("TelescopeMatching",           { fg = p.yellow, bold = true })

  -- ─── fzf-lua ─────────────────────────────────────────────────────────
  hi("FzfLuaNormal",                { fg = p.fg1,    bg = p.bg0 })
  hi("FzfLuaBorder",                { fg = p.bg3,    bg = p.bg0 })
  hi("FzfLuaTitle",                 { fg = p.yellow, bg = p.bg0, bold = true })
  hi("FzfLuaPrompt",                { fg = p.orange })
  hi("FzfLuaPointer",               { fg = p.orange })
  hi("FzfLuaMarker",                { fg = p.purple })
  hi("FzfLuaFzfNormal",             { fg = p.fg1 })
  hi("FzfLuaFzfMatch",              { fg = p.yellow, bold = true })
  hi("FzfLuaFzfBorder",             { fg = p.bg3 })
  hi("FzfLuaFzfScrollbar",          { fg = p.bg4 })
  hi("FzfLuaFzfSeparator",          { fg = p.bg3 })
  hi("FzfLuaFzfGutter",             { bg = p.bg0 })
  hi("FzfLuaFzfCursorLine",         { bg = p.bg1 })
  hi("FzfLuaFzfQuery",              { fg = p.fg1 })
  hi("FzfLuaFzfInfo",               { fg = p.fg3 })
  hi("FzfLuaFzfPrompt",             { fg = p.orange })
  hi("FzfLuaFzfPointer",            { fg = p.orange })
  hi("FzfLuaFzfMarker",             { fg = p.purple })
  hi("FzfLuaFzfSpinner",            { fg = p.yellow })
  hi("FzfLuaFzfHeader",             { fg = p.blue })
  hi("FzfLuaHeaderBind",            { fg = p.yellow })
  hi("FzfLuaHeaderText",            { fg = p.fg3 })
  hi("FzfLuaPathColNr",             { fg = p.purple })
  hi("FzfLuaPathLineNr",            { fg = p.green })
  hi("FzfLuaBufName",               { fg = p.blue })
  hi("FzfLuaBufNr",                 { fg = p.purple })
  hi("FzfLuaBufFlagCur",            { fg = p.orange })
  hi("FzfLuaBufFlagAlt",            { fg = p.yellow })
  hi("FzfLuaTabTitle",              { fg = p.blue, bold = true })
  hi("FzfLuaTabMarker",             { fg = p.orange })

  -- ─── Gitsigns ────────────────────────────────────────────────────────
  hi("GitSignsAdd",                 { fg = p.green })
  hi("GitSignsChange",              { fg = p.yellow })
  hi("GitSignsDelete",              { fg = p.red })
  hi("GitSignsAddNr",               { fg = p.green })
  hi("GitSignsChangeNr",            { fg = p.yellow })
  hi("GitSignsDeleteNr",            { fg = p.red })
  hi("GitSignsAddLn",               { bg = p.bg1 })
  hi("GitSignsChangeLn",            { bg = p.bg1 })
  hi("GitSignsAddPreview",          { fg = p.green })
  hi("GitSignsDeletePreview",       { fg = p.red })
  hi("GitSignsCurrentLineBlame",    { fg = p.bg4 })
  hi("GitSignsAddInline",           { fg = p.bg0, bg = p.green })
  hi("GitSignsDeleteInline",        { fg = p.bg0, bg = p.red })
  hi("GitSignsChangeInline",        { fg = p.bg0, bg = p.yellow })

  -- ─── nvim-tree / neo-tree ────────────────────────────────────────────
  hi("NvimTreeNormal",              { fg = p.fg1,    bg = p.bg0 })
  hi("NvimTreeNormalNC",            { fg = p.fg2,    bg = p.bg0 })
  hi("NvimTreeRootFolder",          { fg = p.yellow, bold = true })
  hi("NvimTreeGitDirty",            { fg = p.yellow })
  hi("NvimTreeGitNew",              { fg = p.green })
  hi("NvimTreeGitDeleted",          { fg = p.red })
  hi("NvimTreeGitIgnored",          { fg = p.bg4 })
  hi("NvimTreeFolderName",          { fg = p.blue })
  hi("NvimTreeFolderIcon",          { fg = p.blue })
  hi("NvimTreeOpenedFolderName",    { fg = p.blue, bold = true })
  hi("NvimTreeEmptyFolderName",     { fg = p.fg3 })
  hi("NvimTreeSymlink",             { fg = p.aqua })
  hi("NvimTreeImageFile",           { fg = p.purple })
  hi("NvimTreeExecFile",            { fg = p.green })
  hi("NvimTreeSpecialFile",         { fg = p.yellow })
  hi("NvimTreeIndentMarker",        { fg = p.bg3 })
  hi("NvimTreeWinSeparator",        { fg = p.bg3 })
  hi("NvimTreeFileIcon",            { fg = p.fg2 })
  hi("NvimTreeOpenedFile",          { fg = p.green })

  hi("NeoTreeNormal",               { fg = p.fg1,    bg = p.bg0 })
  hi("NeoTreeNormalNC",             { fg = p.fg2,    bg = p.bg0 })
  hi("NeoTreeDirectoryName",        { fg = p.blue })
  hi("NeoTreeDirectoryIcon",        { fg = p.blue })
  hi("NeoTreeRootName",             { fg = p.yellow, bold = true })
  hi("NeoTreeFileName",             { fg = p.fg1 })
  hi("NeoTreeFileIcon",             { fg = p.fg2 })
  hi("NeoTreeFileNameOpened",       { fg = p.green })
  hi("NeoTreeGitAdded",             { fg = p.green })
  hi("NeoTreeGitConflict",          { fg = p.red, bold = true })
  hi("NeoTreeGitDeleted",           { fg = p.red })
  hi("NeoTreeGitIgnored",           { fg = p.bg4 })
  hi("NeoTreeGitModified",          { fg = p.yellow })
  hi("NeoTreeGitUnstaged",          { fg = p.orange })
  hi("NeoTreeGitUntracked",         { fg = p.green })
  hi("NeoTreeGitStaged",            { fg = p.green })
  hi("NeoTreeTabActive",            { bold = true })
  hi("NeoTreeTabInactive",          { fg = p.fg3 })
  hi("NeoTreeTabSeparatorActive",   { fg = p.orange })
  hi("NeoTreeTabSeparatorInactive", { fg = p.bg3 })
  hi("NeoTreeIndentMarker",         { fg = p.bg3 })
  hi("NeoTreeExpander",             { fg = p.bg4 })
  hi("NeoTreeSymbolicLinkTarget",   { fg = p.aqua })

  -- ─── which-key ───────────────────────────────────────────────────────
  hi("WhichKey",                    { fg = p.orange })
  hi("WhichKeyGroup",               { fg = p.blue })
  hi("WhichKeyDesc",                { fg = p.fg1 })
  hi("WhichKeyValue",               { fg = p.fg3 })
  hi("WhichKeySeparator",           { fg = p.bg4 })
  hi("WhichKeyBorder",              { fg = p.bg3 })
  hi("WhichKeyNormal",              { bg = p.bg1 })
  hi("WhichKeyTitle",               { fg = p.yellow, bold = true })

  -- ─── indent-blankline / mini.indentscope ─────────────────────────────
  hi("IblIndent",                   { fg = p.bg2 })
  hi("IblScope",                    { fg = p.bg3 })
  hi("IblWhitespace",               { fg = p.bg2 })
  hi("MiniIndentscopeSymbol",       { fg = p.orange })

  -- ─── lualine (semantic link targets) ─────────────────────────────────
  hi("GruuvyStatusLineMode",        { fg = p.bg0, bg = p.orange, bold = true })
  hi("GruuvyStatusLineModeInsert",  { fg = p.bg0, bg = p.green,  bold = true })
  hi("GruuvyStatusLineModeVisual",  { fg = p.bg0, bg = p.purple, bold = true })
  hi("GruuvyStatusLineModeCmd",     { fg = p.bg0, bg = p.red,    bold = true })
  hi("GruuvyStatusLineModeReplace", { fg = p.bg0, bg = p.aqua,   bold = true })

  -- ─── Noice ───────────────────────────────────────────────────────────
  hi("NoicePopup",                  { fg = p.fg1,    bg = p.bg1 })
  hi("NoicePopupBorder",            { fg = p.bg3,    bg = p.bg1 })
  hi("NoiceCmdlinePopup",           { fg = p.fg1,    bg = p.bg1 })
  hi("NoiceCmdlinePopupBorder",     { fg = p.bg3,    bg = p.bg1 })
  hi("NoiceCmdlinePopupTitle",      { fg = p.yellow, bg = p.bg1, bold = true })
  hi("NoiceCmdlineIcon",            { fg = p.orange })
  hi("NoiceCmdlineIconSearch",      { fg = p.yellow })
  hi("NoiceConfirm",                { fg = p.fg1,    bg = p.bg1 })
  hi("NoiceConfirmBorder",          { fg = p.orange, bg = p.bg1 })
  hi("NoiceMini",                   { fg = p.fg2,    bg = p.bg1 })
  hi("NoiceFormatTitle",            { fg = p.orange, bold = true })
  hi("NoiceFormatEvent",            { fg = p.fg3 })
  hi("NoiceFormatKind",             { fg = p.blue })
  hi("NoiceFormatDate",             { fg = p.fg3 })
  hi("NoiceFormatLevelTrace",       { fg = p.purple })
  hi("NoiceFormatLevelDebug",       { fg = p.fg3 })
  hi("NoiceFormatLevelInfo",        { fg = p.blue })
  hi("NoiceFormatLevelWarn",        { fg = p.yellow })
  hi("NoiceFormatLevelError",       { fg = p.red })
  hi("NoiceLspProgressTitle",       { fg = p.fg2 })
  hi("NoiceLspProgressClient",      { fg = p.yellow, bold = true })
  hi("NoiceLspProgressSpinner",     { fg = p.orange })

  -- ─── mini.statusline / mini.tabline ──────────────────────────────────
  hi("MiniStatuslineModeNormal",    { fg = p.bg0, bg = p.orange, bold = true })
  hi("MiniStatuslineModeInsert",    { fg = p.bg0, bg = p.green,  bold = true })
  hi("MiniStatuslineModeVisual",    { fg = p.bg0, bg = p.purple, bold = true })
  hi("MiniStatuslineModeCommand",   { fg = p.bg0, bg = p.red,    bold = true })
  hi("MiniStatuslineModeReplace",   { fg = p.bg0, bg = p.aqua,   bold = true })
  hi("MiniStatuslineInactive",      { fg = p.fg3, bg = p.bg1 })
  hi("MiniStatuslineFilename",      { fg = p.fg2, bg = p.bg1 })
  hi("MiniStatuslineFileinfo",      { fg = p.fg3, bg = p.bg1 })
  hi("MiniStatuslineDevinfo",       { fg = p.fg2, bg = p.bg2 })
  hi("MiniTablineCurrent",          { fg = p.fg1, bg = p.bg0, bold = true })
  hi("MiniTablineVisible",          { fg = p.fg3, bg = p.bg1 })
  hi("MiniTablineHidden",           { fg = p.fg3, bg = p.bg1 })
  hi("MiniTablineModifiedCurrent",  { fg = p.yellow, bg = p.bg0, bold = true })
  hi("MiniTablineModifiedVisible",  { fg = p.yellow, bg = p.bg1 })
  hi("MiniTablineModifiedHidden",   { fg = p.yellow, bg = p.bg1 })
  hi("MiniTablineFill",             { bg = p.bg1 })
  hi("MiniTablineTabpagesection",   { fg = p.fg1, bg = p.bg3, bold = true })

  -- ─── flash.nvim ──────────────────────────────────────────────────────
  hi("FlashBackdrop",               { fg = p.fg3 })
  hi("FlashCurrent",                { fg = p.bg0, bg = p.orange, bold = true })
  hi("FlashLabel",                  { fg = p.bg0, bg = p.yellow, bold = true })
  hi("FlashMatch",                  { fg = p.bg0, bg = p.blue })
  hi("FlashPrompt",                 { fg = p.orange, bold = true })
  hi("FlashPromptIcon",             { fg = p.orange })

  -- ─── Trouble ─────────────────────────────────────────────────────────
  hi("TroubleNormal",               { fg = p.fg1, bg = p.bg0 })
  hi("TroubleNormalNC",             { fg = p.fg2, bg = p.bg0 })
  hi("TroubleText",                 { fg = p.fg1 })
  hi("TroubleCount",                { fg = p.purple, bold = true })
  hi("TroubleIconError",            { fg = p.red })
  hi("TroubleIconWarn",             { fg = p.yellow })
  hi("TroubleIconInfo",             { fg = p.blue })
  hi("TroubleIconHint",             { fg = p.aqua })
  hi("TroubleCode",                 { fg = p.fg3 })
  hi("TroubleFile",                 { fg = p.blue })
  hi("TroubleFoldIcon",             { fg = p.orange })
  hi("TroubleIndent",               { fg = p.bg3 })
  hi("TroublePos",                  { fg = p.purple })
  hi("TroubleSource",               { fg = p.fg3 })

  -- ─── Illuminate ──────────────────────────────────────────────────────
  hi("IlluminatedWordText",         { bg = p.bg2, underline = true })
  hi("IlluminatedWordRead",         { bg = p.bg2, underline = true })
  hi("IlluminatedWordWrite",        { bg = p.bg2, underline = true })

  -- ─── Lazy.nvim ───────────────────────────────────────────────────────
  hi("LazyNormal",                  { fg = p.fg1, bg = p.bg1 })
  hi("LazyBorder",                  { fg = p.bg3, bg = p.bg1 })
  hi("LazyButton",                  { fg = p.fg1, bg = p.bg2 })
  hi("LazyButtonActive",            { fg = p.fg0, bg = p.bg3, bold = true })
  hi("LazyH1",                      { fg = p.yellow, bold = true })
  hi("LazyH2",                      { fg = p.orange, bold = true })
  hi("LazyComment",                 { fg = p.bg4 })
  hi("LazyCommit",                  { fg = p.purple })
  hi("LazyCommitIssue",             { fg = p.red })
  hi("LazyCommitType",              { fg = p.yellow })
  hi("LazyCommitScope",             { fg = p.orange })
  hi("LazyDimmed",                  { fg = p.fg3 })
  hi("LazyDir",                     { fg = p.blue })
  hi("LazyUrl",                     { fg = p.aqua, underline = true })
  hi("LazyLocal",                   { fg = p.orange })
  hi("LazyProgressTodo",            { fg = p.bg3 })
  hi("LazyProgressDone",            { fg = p.green })
  hi("LazySpecial",                 { fg = p.orange })
  hi("LazyReasonPlugin",            { fg = p.blue })
  hi("LazyReasonEvent",             { fg = p.orange })
  hi("LazyReasonKeys",              { fg = p.yellow })
  hi("LazyReasonCmd",               { fg = p.green })
  hi("LazyReasonFt",                { fg = p.purple })
  hi("LazyReasonImport",            { fg = p.aqua })

  -- ─── Mason ───────────────────────────────────────────────────────────
  hi("MasonNormal",                 { fg = p.fg1, bg = p.bg1 })
  hi("MasonHeader",                 { fg = p.bg0, bg = p.orange, bold = true })
  hi("MasonHeaderSecondary",        { fg = p.bg0, bg = p.yellow, bold = true })
  hi("MasonHighlight",              { fg = p.orange })
  hi("MasonHighlightBlock",         { fg = p.bg0, bg = p.orange })
  hi("MasonHighlightBlockBold",     { fg = p.bg0, bg = p.orange, bold = true })
  hi("MasonHighlightSecondary",     { fg = p.yellow })
  hi("MasonHighlightBlockSecondary",{ fg = p.bg0, bg = p.yellow })
  hi("MasonHighlightBlockBoldSecondary", { fg = p.bg0, bg = p.yellow, bold = true })
  hi("MasonLink",                   { fg = p.aqua, underline = true })
  hi("MasonMuted",                  { fg = p.fg3 })
  hi("MasonMutedBlock",             { fg = p.fg3, bg = p.bg2 })
  hi("MasonError",                  { fg = p.red })
  hi("MasonWarning",                { fg = p.yellow })
  hi("MasonHeading",                { fg = p.fg1, bold = true, underline = true })

  -- ─── Snacks.nvim ─────────────────────────────────────────────────────
  hi("SnacksNormal",                { fg = p.fg1, bg = p.bg1 })
  hi("SnacksBorder",                { fg = p.bg3, bg = p.bg1 })
  hi("SnacksNormalNC",              { fg = p.fg2, bg = p.bg1 })
  hi("SnacksDashboardHeader",       { fg = p.yellow, bold = true })
  hi("SnacksDashboardTitle",        { fg = p.orange, bold = true })
  hi("SnacksDashboardFooter",       { fg = p.fg3 })
  hi("SnacksDashboardDesc",         { fg = p.fg2 })
  hi("SnacksDashboardKey",          { fg = p.yellow, bold = true })
  hi("SnacksDashboardIcon",         { fg = p.orange })
  hi("SnacksDashboardSpecial",      { fg = p.orange })
  hi("SnacksIndent",                { fg = p.bg2 })
  hi("SnacksIndentScope",           { fg = p.bg3 })
  hi("SnacksNotifier",              { fg = p.fg1, bg = p.bg1 })
  hi("SnacksNotifierBorder",        { fg = p.bg3, bg = p.bg1 })
  hi("SnacksNotifierIconError",     { fg = p.red })
  hi("SnacksNotifierIconWarn",      { fg = p.yellow })
  hi("SnacksNotifierIconInfo",      { fg = p.blue })
  hi("SnacksNotifierIconDebug",     { fg = p.fg3 })
  hi("SnacksNotifierIconTrace",     { fg = p.purple })
  hi("SnacksNotifierTitleError",    { fg = p.red, bold = true })
  hi("SnacksNotifierTitleWarn",     { fg = p.yellow, bold = true })
  hi("SnacksNotifierTitleInfo",     { fg = p.blue, bold = true })
  hi("SnacksNotifierTitleDebug",    { fg = p.fg3, bold = true })
  hi("SnacksNotifierTitleTrace",    { fg = p.purple, bold = true })
  hi("SnacksPicker",                { fg = p.fg1, bg = p.bg0 })
  hi("SnacksPickerBorder",          { fg = p.bg3, bg = p.bg0 })
  hi("SnacksPickerTitle",           { fg = p.yellow, bg = p.bg0, bold = true })
  hi("SnacksPickerSearch",          { fg = p.orange })
  hi("SnacksPickerMatch",           { fg = p.yellow, bold = true })
  hi("SnacksPickerSelected",        { fg = p.purple })
  hi("SnacksPickerCurrent",         { fg = p.fg0, bg = p.bg2, bold = true })
  hi("SnacksPickerPrompt",          { fg = p.orange })
  hi("SnacksPickerPreview",         { fg = p.fg1, bg = p.bg0 })
  hi("SnacksPickerPreviewBorder",   { fg = p.bg3, bg = p.bg0 })
  hi("SnacksPickerPreviewTitle",    { fg = p.green, bold = true })

  -- ─── Render-markdown ─────────────────────────────────────────────────
  hi("RenderMarkdownH1Bg",          { bg = p.bg2 })
  hi("RenderMarkdownH2Bg",          { bg = p.bg2 })
  hi("RenderMarkdownH3Bg",          { bg = p.bg1 })
  hi("RenderMarkdownH4Bg",          { bg = p.bg1 })
  hi("RenderMarkdownH1",            { fg = p.yellow, bold = true })
  hi("RenderMarkdownH2",            { fg = p.orange, bold = true })
  hi("RenderMarkdownH3",            { fg = p.green,  bold = true })
  hi("RenderMarkdownH4",            { fg = p.blue,   bold = true })
  hi("RenderMarkdownH5",            { fg = p.purple, bold = true })
  hi("RenderMarkdownH6",            { fg = p.aqua,   bold = true })
  hi("RenderMarkdownCode",          { bg = p.bg1 })
  hi("RenderMarkdownCodeInline",    { bg = p.bg2 })
  hi("RenderMarkdownBullet",        { fg = p.orange })
  hi("RenderMarkdownLink",          { fg = p.blue, underline = true })
  hi("RenderMarkdownQuote",         { fg = p.fg3 })
  hi("RenderMarkdownTableHead",     { fg = p.yellow, bold = true })
  hi("RenderMarkdownTableRow",      { fg = p.fg1 })
  hi("RenderMarkdownTableFill",     { fg = p.bg3 })
  hi("RenderMarkdownChecked",       { fg = p.green })
  hi("RenderMarkdownUnchecked",     { fg = p.fg3 })
  hi("RenderMarkdownTodo",          { fg = p.bg0, bg = p.yellow, bold = true })
  hi("RenderMarkdownSuccess",       { fg = p.green })
  hi("RenderMarkdownInfo",          { fg = p.blue })
  hi("RenderMarkdownHint",          { fg = p.aqua })
  hi("RenderMarkdownWarn",          { fg = p.yellow })
  hi("RenderMarkdownError",         { fg = p.red })
  hi("RenderMarkdownDash",          { fg = p.bg3 })

  -- ─── nvim-dap ────────────────────────────────────────────────────────
  hi("DapBreakpoint",               { fg = p.red })
  hi("DapBreakpointCondition",      { fg = p.yellow })
  hi("DapBreakpointRejected",       { fg = p.fg3 })
  hi("DapLogPoint",                 { fg = p.blue })
  hi("DapStopped",                  { fg = p.green })
  hi("DapStoppedLine",              { bg = p.bg2 })

  -- ─── Notify ──────────────────────────────────────────────────────────
  hi("NotifyBackground",            { bg = p.bg1 })
  hi("NotifyERRORBorder",           { fg = p.red })
  hi("NotifyWARNBorder",            { fg = p.yellow })
  hi("NotifyINFOBorder",            { fg = p.blue })
  hi("NotifyDEBUGBorder",           { fg = p.fg3 })
  hi("NotifyTRACEBorder",           { fg = p.purple })
  hi("NotifyERRORIcon",             { fg = p.red })
  hi("NotifyWARNIcon",              { fg = p.yellow })
  hi("NotifyINFOIcon",              { fg = p.blue })
  hi("NotifyDEBUGIcon",             { fg = p.fg3 })
  hi("NotifyTRACEIcon",             { fg = p.purple })
  hi("NotifyERRORTitle",            { fg = p.red,    bold = true })
  hi("NotifyWARNTitle",             { fg = p.yellow, bold = true })
  hi("NotifyINFOTitle",             { fg = p.blue,   bold = true })
  hi("NotifyDEBUGTitle",            { fg = p.fg3,    bold = true })
  hi("NotifyTRACETitle",            { fg = p.purple, bold = true })
  hi("NotifyERRORBody",             { fg = p.fg1 })
  hi("NotifyWARNBody",              { fg = p.fg1 })
  hi("NotifyINFOBody",              { fg = p.fg1 })
  hi("NotifyDEBUGBody",             { fg = p.fg2 })
  hi("NotifyTRACEBody",             { fg = p.fg2 })

  -- ─── Leap ────────────────────────────────────────────────────────────
  hi("LeapMatch",                   { fg = p.bg0, bg = p.orange, bold = true })
  hi("LeapLabel",                   { fg = p.bg0, bg = p.yellow, bold = true })
  hi("LeapBackdrop",                { fg = p.fg3 })

  -- ─── Aerial / Outline ────────────────────────────────────────────────
  hi("AerialLine",                  { bg = p.bg2 })
  hi("AerialNormal",                { fg = p.fg1 })
  hi("AerialGuide",                 { fg = p.bg3 })
  hi("AerialClass",                 { fg = p.blue })
  hi("AerialFunction",              { fg = p.green })
  hi("AerialMethod",                { fg = p.green })
  hi("AerialConstructor",           { fg = p.blue })
  hi("AerialEnum",                  { fg = p.blue })
  hi("AerialVariable",              { fg = p.fg1 })
  hi("AerialConstant",              { fg = p.purple })
  hi("AerialModule",                { fg = p.yellow })
  hi("AerialInterface",             { fg = p.blue })
  hi("AerialStruct",                { fg = p.blue })
  hi("AerialField",                 { fg = p.aqua })
  hi("AerialProperty",              { fg = p.aqua })
  hi("AerialArray",                 { fg = p.blue })
  hi("AerialObject",                { fg = p.blue })
  hi("AerialNull",                  { fg = p.purple })
  hi("AerialBoolean",               { fg = p.purple })
  hi("AerialNumber",                { fg = p.purple })
  hi("AerialString",                { fg = p.green })
  hi("AerialPackage",               { fg = p.yellow })
  hi("AerialTypeParameter",         { fg = p.blue })
  hi("AerialKey",                   { fg = p.yellow })
  hi("AerialNamespace",             { fg = p.yellow })
  hi("AerialEvent",                 { fg = p.orange })
  hi("AerialOperator",              { fg = p.fg1 })
  hi("AerialFile",                  { fg = p.yellow })

  -- ─── Alpha / Dashboard ───────────────────────────────────────────────
  hi("AlphaHeader",                 { fg = p.yellow })
  hi("AlphaButtons",                { fg = p.orange })
  hi("AlphaShortcut",               { fg = p.yellow, bold = true })
  hi("AlphaFooter",                 { fg = p.fg3 })

  -- ─── nvim-ufo ────────────────────────────────────────────────────────
  hi("UfoFoldedFg",                 { fg = p.fg2 })
  hi("UfoFoldedBg",                 { bg = p.bg2 })
  hi("UfoCursorFoldedLine",         { bg = p.bg2 })

  -- ─── Semantic token highlights ───────────────────────────────────────
  hi("@lsp.type.class",             { link = "@type" })
  hi("@lsp.type.comment",           { link = "@comment" })
  hi("@lsp.type.decorator",         { link = "@attribute" })
  hi("@lsp.type.enum",              { link = "@type" })
  hi("@lsp.type.enumMember",        { link = "@constant" })
  hi("@lsp.type.function",          { link = "@function" })
  hi("@lsp.type.interface",         { link = "@type" })
  hi("@lsp.type.macro",             { link = "@function.macro" })
  hi("@lsp.type.method",            { link = "@function.method" })
  hi("@lsp.type.modifier",          { link = "@keyword.modifier" })
  hi("@lsp.type.namespace",         { link = "@module" })
  hi("@lsp.type.number",            { link = "@number" })
  hi("@lsp.type.operator",          { link = "@operator" })
  hi("@lsp.type.parameter",         { link = "@variable.parameter" })
  hi("@lsp.type.property",          { link = "@property" })
  hi("@lsp.type.selfKeyword",       { link = "@variable.builtin" })
  hi("@lsp.type.string",            { link = "@string" })
  hi("@lsp.type.struct",            { link = "@type" })
  hi("@lsp.type.type",              { link = "@type" })
  hi("@lsp.type.typeParameter",     { link = "@type.definition" })
  hi("@lsp.type.variable",          { link = "@variable" })
  hi("@lsp.mod.deprecated",         { strikethrough = true })
  hi("@lsp.mod.readonly",           { fg = p.fg1 })
  hi("@lsp.mod.static",             {})
  hi("@lsp.mod.defaultLibrary",     { bold = bold })
end

return M
